server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://farm-data-service.farm-data.svc.cluster.local:8000/;
    }

    location /storage/ {
        proxy_pass http://storage-service.storage.svc.cluster.local:8000/;
    }
}
