apiVersion: v1
kind: Namespace
metadata:
  name: farm-db-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
