apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: farm-db-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: farm-data-service
  namespace: farm-db-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iot-simulator
  namespace: farm-db-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: storage-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-service
  namespace: storage-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend-svc
  labels:
    app.kubernetes.io/part-of: smartfarming
    environment: local
